# Generated by Django 5.1.4 on 2026-06-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('kind', models.CharField(choices=[('postgres', 'PostgreSQL'), ('mysql', 'MySQL')], default='postgres', max_length=20)),
                ('host', models.CharField(default='localhost', max_length=255)),
                ('port', models.IntegerField(default=5432)),
                ('dbname', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
