# Generated by Django 5.1.4 on 2026-06-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plansnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansnapshot',
            name='plan_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
