# Generated by Django 5.1.15 on 2026-06-12 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plansnapshot_plan_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=40)),
                ('kind', models.CharField(max_length=16)),
                ('target', models.CharField(max_length=255)),
                ('dbname', models.CharField(max_length=255)),
                ('data', models.BinaryField()),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='core.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
