# Generated by Django 5.1.15 on 2026-06-12 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_backup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sql', models.TextField()),
                ('read_only', models.BooleanField(default=True)),
                ('status', models.CharField(default='ok', max_length=8)),
                ('rowcount', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.connection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
