# Generated by Django 5.2.5 on 2026-09-23 08:12

import django.utils.timezone
from django.db import migrations, models


def backfill_last_used_at(apps, schema_editor):
    """The AddField step just above stamps every existing row with the single
    moment this migration ran (Django evaluates the callable default once for
    the whole ALTER TABLE), which would bunch every pre-existing connection
    together and erase their prior relative order. Re-derive it from
    created_at instead, so existing rows keep ordering the same as before
    this migration — only real future use moves them."""
    Connection = apps.get_model('core', 'Connection')
    for connection in Connection.objects.all():
        connection.last_used_at = connection.created_at
        connection.save(update_fields=['last_used_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_command'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connection',
            options={'ordering': ['-last_used_at']},
        ),
        migrations.AddField(
            model_name='connection',
            name='last_used_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(backfill_last_used_at, migrations.RunPython.noop),
    ]
