# Generated by Django 5.2.5 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_connection_last_used_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='environment',
            field=models.CharField(blank=True, choices=[('', '—'), ('dev', 'Dev'), ('staging', 'Staging'), ('prod', 'Prod')], default='', max_length=20),
        ),
    ]
