# Generated by Django 5.2.5 on 2026-10-07 22:54

import core.secret_store
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_connection_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='password',
            field=core.secret_store.SecretField(blank=True),
        ),
    ]
