from django.urls import include, path

from core import views

urlpatterns = [
    # Exposes set_language, which the header JP/EN toggle POSTs to. It records the
    # choice in a cookie (no session needed) and redirects back to `next`.
    path("i18n/", include("django.conf.urls.i18n")),
    path("", views.index, name="index"),
    path("connect", views.connect, name="connect"),
    path("c/<int:pk>/", views.workspace, name="workspace"),
    path("c/<int:pk>/overview", views.overview, name="overview"),
    path("c/<int:pk>/table", views.table_detail, name="table_detail"),
    path("c/<int:pk>/table/rename", views.table_rename, name="table_rename"),
    path("c/<int:pk>/table/truncate", views.table_truncate, name="table_truncate"),
    path("c/<int:pk>/table/drop", views.table_drop, name="table_drop"),
    path("c/<int:pk>/table/dump", views.table_dump, name="table_dump"),
    path("c/<int:pk>/columns/add", views.column_add, name="column_add"),
    path("c/<int:pk>/columns/rename", views.column_rename, name="column_rename"),
    path("c/<int:pk>/columns/drop", views.column_drop, name="column_drop"),
    path("c/<int:pk>/columns/type", views.column_retype, name="column_retype"),
    path("c/<int:pk>/columns/null", views.column_set_null, name="column_set_null"),
    path("c/<int:pk>/columns/default", views.column_set_default, name="column_set_default"),
    path("c/<int:pk>/indexes/create", views.index_create, name="index_create"),
    path("c/<int:pk>/indexes/drop", views.index_drop, name="index_drop"),
    path("c/<int:pk>/lab", views.index_lab, name="index_lab"),
    path("c/<int:pk>/lab/preview", views.index_lab_preview, name="index_lab_preview"),
    path("c/<int:pk>/query", views.query, name="query"),
    path("c/<int:pk>/query/run", views.query_run, name="query_run"),
    path("c/<int:pk>/query/export", views.query_export, name="query_export"),
    path("c/<int:pk>/history", views.history, name="history"),
    path("c/<int:pk>/history/clear", views.history_clear, name="history_clear"),
    path("c/<int:pk>/explain", views.explain_run, name="explain_run"),
    path("c/<int:pk>/scale", views.scale_run, name="scale_run"),
    path("c/<int:pk>/snapshots", views.snapshots, name="snapshots"),
    path("c/<int:pk>/snapshots/save", views.snapshot_save, name="snapshot_save"),
    path("c/<int:pk>/snapshots/plan", views.snapshot_plan, name="snapshot_plan"),
    path("c/<int:pk>/snapshots/delete", views.snapshot_delete, name="snapshot_delete"),
    path("c/<int:pk>/snapshots/diff", views.snapshot_diff, name="snapshot_diff"),
    path("c/<int:pk>/activity", views.activity, name="activity"),
    path("c/<int:pk>/activity/cancel", views.activity_cancel, name="activity_cancel"),
    path("c/<int:pk>/activity/kill", views.activity_kill, name="activity_kill"),
    path("c/<int:pk>/locks", views.locks, name="locks"),
    path("c/<int:pk>/locks/cancel", views.locks_cancel, name="locks_cancel"),
    path("c/<int:pk>/locks/kill", views.locks_kill, name="locks_kill"),
    path("c/<int:pk>/replication", views.replication, name="replication"),
    path("c/<int:pk>/replication/slots/create", views.slot_create, name="slot_create"),
    path("c/<int:pk>/replication/slots/drop", views.slot_drop, name="slot_drop"),
    path("c/<int:pk>/health", views.health, name="health"),
    path("c/<int:pk>/objects", views.objects, name="objects"),
    path("c/<int:pk>/databases/create", views.database_create, name="database_create"),
    path("c/<int:pk>/databases/drop", views.database_drop, name="database_drop"),
    path("c/<int:pk>/databases/rename", views.database_rename, name="database_rename"),
    path("c/<int:pk>/databases/dump", views.database_dump, name="database_dump"),
    path("c/<int:pk>/databases/restore", views.database_restore, name="database_restore"),
    path("c/<int:pk>/backups", views.backups, name="backups"),
    path("c/<int:pk>/backups/download", views.backup_download, name="backup_download"),
    path("c/<int:pk>/backups/delete", views.backup_delete, name="backup_delete"),
    path("c/<int:pk>/backups/restore", views.backup_restore, name="backup_restore"),
    path("c/<int:pk>/schemas/create", views.schema_create, name="schema_create"),
    path("c/<int:pk>/schemas/alter", views.schema_alter, name="schema_alter"),
    path("c/<int:pk>/schemas/delete", views.schema_delete, name="schema_delete"),
    path("c/<int:pk>/roles/create", views.role_create, name="role_create"),
    path("c/<int:pk>/roles/alter", views.role_alter, name="role_alter"),
    path("c/<int:pk>/roles/delete", views.role_delete, name="role_delete"),
    path("c/<int:pk>/settings", views.settings, name="settings"),
    path("c/<int:pk>/settings/update", views.settings_update, name="settings_update"),
    path("c/<int:pk>/settings/reset", views.settings_reset, name="settings_reset"),
]
